### ISSUE TITLE
IntervalLength  TODO for Timeseries object

### ISSUE THREAD

**Issue by gidthup** [DigitaleDeltaOrg/dd-api#14]
The description of the IntervalLength attribute of the Timeseries object contains a TODO for the unit of measure.  There is a relation with the IntervalLength used as queryParameter.
I think we agreed on it being a number of seconds if no unit of measure is specified.
'10min' is a special default value used by DD-OPER.

The Todo needs to be adressed. 
Do we need formal definitions of unit of measures ?
The output could be given in DateTime format too.  'HH:mm:ss.ssss' 

Something to address in the workgroup ?

**Comment by stefhummel** [comment]
De intervalLength komt twee keer voor:
•	In het Timeseries object in de response van /timeseries:
                intervalLength: number 
Hier moet beschreven worden dat deze uitgedrukt wordt in seconds (staat er nu niet)
•	Als query-parameter in het /timeseries end point:
                intervalLength: string, default: 10min
 
Laatstgenoemde query-parameter dient om te kunnen filteren wanneer er voor één location/observationType meerdere tijdseries zijn met verschillende intervallen, b.v. 1min, 10min, 1hr.
Onduidelijk is wat er moet gebeuren wanneer deze parameter niet wordt meegegeven. In feite treedt dan de default waarde in werking: 10 minuten. Men krijgt dan dus alleen maar de 10-minuten series terug. Series waarvan men het interval niet kent, of die non-equidistant zijn, komen dus nooit tevoorschijn. Bij een RWS-systeem dat deze specificatie strikt volg is dan ook expliciet intervalLength=null toegevoegd om de non-equidistante series op te vragen.
 
In alle andere systemen wordt de intervalLength query-parameter gebruikt zoals elke andere filter-parameter: weglaten leidt tot het teruggeven van alles (b.v. alle series voor een location/observationType-combinatie, ongeacht het interval van die series).
 
Goedbeschouwd doen die systemen het dus fout t.o.v. de specificaties. Maar ze handelen wel op de manier zoals het bedoeld is; de specificaties beschrijven een gedrag dat niet de bedoeling was.
 
Voorstel  is om in 2.0.x te accepteren dat er per systeem verschillend wordt gereageerd op het weglaten van de intervalLength query-parameter, en bij 2.2. de default uit de specificaties te verwijderen, zodat het weglaten van intervalLength query-parameter leidt tot het retourneren van alle series die aan de query voldoen.
Het expliciet opvragen van een non-equidistante tijdseries zou dan kunnen door voor intervalLength waarde 0 op te vragen. 
 
Ander punt is dat op termijn de intervalLength query-parameter van het type number moet worden. In eerste instantie blijft hij van het type string, maar de inhoud wordt verondersteld een getal te zijn, met als enige uitzondering ‘10min’; zulks vanwege backwards compatibiliteit.
