### ISSUE TITLE
Extra metadata in ObservationType 

### ISSUE THREAD

**Issue by gidthup** [DigitaleDeltaOrg/dd-api#15]
What would be the approach to include extra attributes in the ObservationType object ?

In DD-API 1.0 there was a key/values array option. That no longer exists.
It is possible to add extra attributes that are not defined in the DD-API without 'breaking' it. It is up to the receiver to accept/ignore the extra elements.

Do we need to formalise this ?  

FYI: We want to include extra Aquo metadata attributes that are currently part of the webservices interface between RWS Advies-DL and WaterInfo website.

**Comment by stefhummel** [comment]
Issue inderdaad gesloten, presentatiemateriaal toegevoegd aan #22.
