### ISSUE TITLE
Reference to used domain standards (ie quality, additional-quality, etc)

### ISSUE THREAD

**Issue by gidthup** [DigitaleDeltaOrg/dd-api#20]
The DD-(OPER)-API does not specify/enforce domain value standards. AQUO is the preferred standard for RWS and other governmental bodies (provincies)  but it is not possible to derive this from the timeseries message content. For instance the same values of quantity and additional quantity can have a different meanings depending on the Provider system.

Suggestion:  Formalise one or more attributes in the Provider object to specify, or provide a reference to, metadata or standards.

**Comment by stefhummel** [comment]
Getracht wordt om generiek mechanisme te definiëren voor het verwijzen naar metadata. Dit moet dan de gewenste functionaliteit van #22, #20, en #15 dekken.

**Comment by stefhummel** [comment]
Hier is en wordt nader aan gewerkt binnen issue #22.
