### ISSUE TITLE
Create labels for DD-OPER and DD-API on Github

### ISSUE THREAD

**Issue by wkramer** [DigitaleDeltaOrg/dd-api#34]
Some issues are specific for either the DD-API or DD-OPER. Would be nice to have labels when creating issues.

**Comment by stefhummel** [comment]
(Namens DD-werkgroep) De issues gaan voor het grootste deel over zaken die in de DD-OPER en DD-API hetzelfde zijn, b.v. details in de response, mechanisme voor verwijzing naar metadata, filtering mechanisme etcetera. We doen er goed aan om de overeenkomst tussen DD-OPER en DD-API te benadrukken. Aparte labels introduceren zou juist op de verschillen wijzen.
