### ISSUE TITLE
Documentation: Description crsName element not correct. 

### ISSUE THREAD

**Issue by gidthup** [DigitaleDeltaOrg/dd-api#6]
In the description of the crsName datatype there is mentioning that ETRS89 without suffix is equivalent to ETRS89-XYZ. This is not correct as the UoM for the XYZ variant is meters from the reference point. As the GeoJSON structure only allows Lat/Lon/Alt in degrees it is equivalent to ETRS89 Geodetic (EPSG:4258). This needs to be corrected in the description.

**Comment by stefhummel** [comment]
De default voor crsName is WGS84. Als men echter ETRS89 wil gebruiken (zoals bij RWS), dan staat momenteel in de beschrijving dat hiermee ETRS89-XYZ wordt bedoeld. Dit is echter een (metrisch) x/y-systeem, en dus inconsistent met de in GeoJSON gebruikte lat/lon. Om dit consistent te maken veranderen we dus de beschrijving in “met ETRS89 wordt ETRS89-Geodetic bedoeld”.
Wil men toch een metrisch coördinatensysteem gebruiken dan kan dat, maar dan bevat de coordinaten-array in de GeoJSON dus geen lat/lon- maar x/y-coördinaten. Voor de duidelijkheid voegen we dit toe aan de beschrijving van Location.crsName.
De boundingbox-parameter in het /locations end point is altijd in WGS84 omdat er nu geen mogelijkheid is een afwijkend crs te specificeren in het request. Mocht er in de DD-GRID-API worden besloten dat daar een boundingbox-crsName wordt toegevoegd, dan is het goed om dat ook bij de DD-API door te voeren. Voor de volledigheid nemen we ook dat in het commentaar op.

**Comment by gerritsj** [comment]
Ik ben wel benieuwd naar de argumenten van RWS om als default voor ETRS89 i.p.v. WGS84 te kiezen. Voor het Matroos/FEWS-archief gaat RWS namelijk wel voor WGS84 kiezen...

**Comment by GeriWolters** [comment]
Ik denk dat de reden is om te voldoen aan INSPIRE (Europese wetgeving). Voor de volledigheid: RWS gebruikt naast RD en WGS84 ook nog (maar mogelijk niet uitsluitend) ook nog ED50, ED77.

**Comment by gidthup** [comment]
>
> Ik ben wel benieuwd naar de argumenten van RWS om als default voor ETRS89 i.p.v. WGS84 te kiezen. Voor het Matroos/FEWS-archief gaat RWS namelijk wel voor WGS84 kiezen...

RWS overweegt nu ook om voor de NARWL Lijst (Standaard phenomeen locaties) af te stappen van ETRS89 en WGS84 Geodetic te gebruiken. De lijst wordt o.a. in LMWNext , MKKDL en WADAR gebruikt en tzt ook in WaterInfo en andere applicaties.  ETRS89 Geodetic lijkt steeds minder voor de  hand liggend als default...

**Comment by GeriWolters** [comment]
Hoi Jurgen. Ik denk dat INSPIRE er iets mee te maken heeft:

Uit: D2.8.I.1 INSPIRE Specification on Coordinate Reference Systems – Guidelines (europa.eu)<https://inspire.ec.europa.eu/documents/Data_Specifications/INSPIRE_Specification_CRS_v3.0.pdf>

For the horizontal component, INSPIRE will mandate the use of the European Terrestrial Reference System 1989 (ETRS89) for the areas within the geographical scope of ETRS89. The International Terrestrial Reference System (ITRS) or other geodetic coordinate reference systems compliant with ITRS shall be used in areas that are outside the geographical scope of ETRS89. Compliant with the ITRS means that the system definition is based on the definition of the ITRS and there is a well established and described relationship between both systems, according to ISO 19111:2007 Geographic Information – Spatial referencing by coordinates.

ETRS89 is in ieder geval voor AquaDesk als keiharde eis gesteld door RWS. Maar dank voor de info dat RWS overweegt af te stappen van ETRS89 en te kiezen voor WGS84. Maakt het wel eenduidiger voor GeoJSON. Er is namelijk geen standaard voor CRS in GeoJSON…
Gezien het feit dat RWS ook overweegt om de verschillende providers voor het WaterInfo portaal rechtstreeks te benaderen i.p.v. via de DL, is dat ook wel belangrijk. Aan de andere kant… centimeters verschil?

Met vriendelijke groet,

  Geri


Van: Jurgen Boerboom ***@***.***>
Verzonden: zondag 11 juli 2021 17:24
Aan: DigitaleDeltaOrg/dd-api ***@***.***>
CC: Geri Wolters ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [DigitaleDeltaOrg/dd-api] Documentation: Description crsName element not correct. (#6)


Ik ben wel benieuwd naar de argumenten van RWS om als default voor ETRS89 i.p.v. WGS84 te kiezen. Voor het Matroos/FEWS-archief gaat RWS namelijk wel voor WGS84 kiezen...

RWS overweegt nu ook om voor de NARWL Lijst (Standaard phenomeen locaties) af te stappen van ETRS89 en WGS84 Geodetic te gebruiken. De lijst wordt o.a. in LMWNext , MKKDL en WADAR gebruikt en tzt ook in WaterInfo en andere applicaties. ETRS89 Geodetic lijkt steeds minder voor de hand liggend als default...

**Comment by GeriWolters** [comment]
Morgen wordt dit mogelijk besproken binnen de RWS Architecture Board.
Dan gaan we meer horen, denk ik.

Met vriendelijke groet,

  Geri Wolters

Van: Geri Wolters
Verzonden: zondag 11 juli 2021 17:35
Aan: DigitaleDeltaOrg/dd-api ***@***.***>; DigitaleDeltaOrg/dd-api ***@***.***>
CC: Comment ***@***.***>
Onderwerp: RE: [DigitaleDeltaOrg/dd-api] Documentation: Description crsName element not correct. (#6)

Hoi Jurgen. Ik denk dat INSPIRE er iets mee te maken heeft:

Uit: D2.8.I.1 INSPIRE Specification on Coordinate Reference Systems – Guidelines (europa.eu)<https://inspire.ec.europa.eu/documents/Data_Specifications/INSPIRE_Specification_CRS_v3.0.pdf>

For the horizontal component, INSPIRE will mandate the use of the European Terrestrial Reference System 1989 (ETRS89) for the areas within the geographical scope of ETRS89. The International Terrestrial Reference System (ITRS) or other geodetic coordinate reference systems compliant with ITRS shall be used in areas that are outside the geographical scope of ETRS89. Compliant with the ITRS means that the system definition is based on the definition of the ITRS and there is a well established and described relationship between both systems, according to ISO 19111:2007 Geographic Information – Spatial referencing by coordinates.

ETRS89 is in ieder geval voor AquaDesk als keiharde eis gesteld door RWS. Maar dank voor de info dat RWS overweegt af te stappen van ETRS89 en te kiezen voor WGS84. Maakt het wel eenduidiger voor GeoJSON. Er is namelijk geen standaard voor CRS in GeoJSON…
Gezien het feit dat RWS ook overweegt om de verschillende providers voor het WaterInfo portaal rechtstreeks te benaderen i.p.v. via de DL, is dat ook wel belangrijk. Aan de andere kant… centimeters verschil?

Met vriendelijke groet,

  Geri


Van: Jurgen Boerboom ***@***.******@***.***>>
Verzonden: zondag 11 juli 2021 17:24
Aan: DigitaleDeltaOrg/dd-api ***@***.******@***.***>>
CC: Geri Wolters ***@***.******@***.***>>; Comment ***@***.******@***.***>>
Onderwerp: Re: [DigitaleDeltaOrg/dd-api] Documentation: Description crsName element not correct. (#6)


Ik ben wel benieuwd naar de argumenten van RWS om als default voor ETRS89 i.p.v. WGS84 te kiezen. Voor het Matroos/FEWS-archief gaat RWS namelijk wel voor WGS84 kiezen...

RWS overweegt nu ook om voor de NARWL Lijst (Standaard phenomeen locaties) af te stappen van ETRS89 en WGS84 Geodetic te gebruiken. De lijst wordt o.a. in LMWNext , MKKDL en WADAR gebruikt en tzt ook in WaterInfo en andere applicaties. ETRS89 Geodetic lijkt steeds minder voor de hand liggend als default...

**Comment by GeriWolters** [comment]
Ik kreeg dit antwoord van Flip:

------------------------
Dit is gisteren in het BMW architecture board besproken en daar is besloten dat wij gewoon vasthouden aan ETRS. Ben je hier voldoende mee geholpen?
 
Groeten,
Flip
-----------------------

RWS houdt dus vast aan ETRS89, niet WGS84.
