### ISSUE TITLE
Add request option/filter to get timeseries with 'resultTime' since timestamp.

### ISSUE THREAD

**Issue by gidthup** [DigitaleDeltaOrg/dd-api#7]
The only way to find out if data has been modified since it was retrieved is to retrieve the full set again and again and compare it against the earlier received values. This is very inefficient.
It would be useful to have a mechanism to receive only those time-series where there has been a change in value and/or quality codes.

For example, allowing a filter as shown below

/timeseries ?start_time= &end_time= filter 'result_time:ge:2019-09-17T00:00::00'

**Comment by GeriWolters** [comment]
Agreed, although I'd prefer something like LastModified as a name (or last_modified). The correct filter usage would be: /timeseries?filter=LastModified:ge:'2019-09-17T00:00:00'.
Using the filter syntax, this would be implementation specific and not break implementations.

**Comment by gidthup** [comment]
Using LastModified as constraint name makes the request ambiguous as it does not specify against what the service provider needs to do the verification.  In Timeseries response the result_time element provides a timestamp of when the 'value' or 'quality' was changed. Using result-time is there for much clearer for both requestor and service provider.

**Comment by GeriWolters** [comment]
I agree then. Can we agree on using result_time over result-time (as your answer mentioned)?

**Comment by GeriWolters** [comment]
In addition: I would suggest to add this kind of filters to more, if not all, endpoints. This would (at least) make sense for locations and observationtypes.

**Comment by gidthup** [comment]
> 
> 
> I agree then. Can we agree on using result_time over result-time (as your answer mentioned)?

I just noticed in the raml that the actual attribute name in the Event object is 'resultTime'.

**Comment by gidthup** [comment]
A Provider is not required to provide a resultTime as it is defined optional in the RAML and there is no constraint in the documentation. To keep it backward compatible and prevent duplicate information I propose to add to the documentation that in case the resultTime is omitted the resultTime can be considered to have the same value as the endTime, or alternatively the timestamp in case the endTime is not available either.

**Comment by gidthup** [comment]
Just having one condition resultTime>=datetime can still provide too many results as all the events with startTime after the given datetime could be included in the selection.  It depends on the business logic in the Provider regarding handling/setting resultTime initially and after an update of the event.  Is the resultTime intially empty or set to be equal to the endTime ?

Could an extra condition like    resultTime:ge:<datetime> AND resultTime:ne:endTime solve this ?

Added this entry just for discussion final solution.

**Comment by gidthup** [comment]
The DD-API /timeseries endpoint already has 3 optional filter parameters for location attributes, observationType attributes and timeseries attributes.
For DD-OPER-API only the filter for timeseries attributes is needed.   Naming wise the new parameter could be named 'filter' as this is the convention in DD-ECO-API and only one filter is needed, but to keep consistency and easier conversion between DD-OPER-API and DD-API requests, the same name as in DD-API will be used:  'timeseriesFilter'

**Comment by gidthup** [comment]
/timeseriesFilter was added on DD-OPER /timeseries in intermediate version DD_OPER 2.1.0.1 to allow resultTime filter to be used by RWS projects WADAR and LMWNext.  The changes has been included into the 'prepare_v202' branch.

**Comment by stefhummel** [comment]
Na team discussie:
In versie 2.1 als opnemen als optioneel te implementeren query parameter. Is typisch een kandidaat voor een generieke filterparameter, maar dat kan nog niet omdat de discussie over generieke filtering syntax nog loopt.
Wel alvast een issue aanmaken deze onder milestone 3.0 hangen. Is gebeurd, zie #40.

**Comment by GeriWolters** [comment]
Deze taak ligt al een tijd open. Iemand die dit op zich wil nemen, of kan deze gesloten worden?

**Comment by gidthup** [comment]
Dit was een RWS verzoek.  Ondertussen hebben we bij  deze extra query parameter al geïmplementeerd op de DD-OPER-API.
met vriendelijke groeten,Jurgen Boerboom.   "Optimism does not alter the Laws of Nature."                                            T´Pol, Vulcan science officer___________________________________________________IT Architect - Complex Systems Integration
Logistics Automation and Optimization / Aviation Competence Center / RWS 
IBM Consulting
IBM Northern EuropeJohan Huizingalaan 765
1066 VH AmsterdamThe Netherlands
Mobile: +31 (0) 6 203 654 81E-mail: ***@***.***
 
 
----- Original message -----From: "Geri Wolters" ***@***.***>To: "DigitaleDeltaOrg/dd-api" ***@***.***>Cc: "Jurgen Boerboom" ***@***.***>, "State change" ***@***.***>Subject: [EXTERNAL] Re: [DigitaleDeltaOrg/dd-api] Add request option/filter to get timeseries with 'resultTime' since timestamp. (#7)Date: Wed, Feb 9, 2022 09:39      Deze taak ligt al een tijd open. Iemand die dit op zich wil nemen, of kan deze gesloten worden? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state. ‍ ‍ ‍ ‍ ‍    ZjQcmQRYFpfptBannerStart  

This Message Is From an External Sender
This message came from outside your organization. ZjQcmQRYFpfptBannerEnd 
 
Deze taak ligt al een tijd open. Iemand die dit op zich wil nemen, of kan deze gesloten worden?
—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
 
Tenzij hierboven anders aangegeven: / Unless stated otherwise above:

IBM Nederland B.V.

Gevestigd te Amsterdam

Inschrijving Handelsregister Amsterdam Nr. 33054214

**Comment by GeriWolters** [comment]
Dank je. Dan zal ik dit issue sluiten,
